//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisposableFixer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisposableFixer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disposable is not disposed..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodInvocation returns an anonymous object that is not disposed..
        /// </summary>
        internal static string AnonymousObjectFromMethodInvocationDescription {
            get {
                return ResourceManager.GetString("AnonymousObjectFromMethodInvocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undisposed anonymous object..
        /// </summary>
        internal static string AnonymousObjectFromMethodInvocationMessageFormat {
            get {
                return ResourceManager.GetString("AnonymousObjectFromMethodInvocationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed anonymous objects from method invocations..
        /// </summary>
        internal static string AnonymousObjectFromMethodInvocationTitle {
            get {
                return ResourceManager.GetString("AnonymousObjectFromMethodInvocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undisposed anonymous object..
        /// </summary>
        internal static string AnonymousObjectFromObjectCreationDescription {
            get {
                return ResourceManager.GetString("AnonymousObjectFromObjectCreationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ObjectCreation returns an object that is not disposed..
        /// </summary>
        internal static string AnonymousObjectFromObjectCreationMessageFormat {
            get {
                return ResourceManager.GetString("AnonymousObjectFromObjectCreationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed anonymous objects from object creations..
        /// </summary>
        internal static string AnonymousObjectFromObjectCreationTitle {
            get {
                return ResourceManager.GetString("AnonymousObjectFromObjectCreationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of method invocation is assigned to a field that is never disposed..
        /// </summary>
        internal static string AssignmendFromMethodInvocationToFieldNotDisposedDescription {
            get {
                return ResourceManager.GetString("AssignmendFromMethodInvocationToFieldNotDisposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not disposed..
        /// </summary>
        internal static string AssignmendFromMethodInvocationToFieldNotDisposedMessageFormat {
            get {
                return ResourceManager.GetString("AssignmendFromMethodInvocationToFieldNotDisposedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed objects assinged to a field, originated from method invocation..
        /// </summary>
        internal static string AssignmendFromMethodInvocationToFieldNotDisposedTitle {
            get {
                return ResourceManager.GetString("AssignmendFromMethodInvocationToFieldNotDisposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of method invocation is assigned to a property that is never disposed..
        /// </summary>
        internal static string AssignmendFromMethodInvocationToPropertyNotDisposedDescription {
            get {
                return ResourceManager.GetString("AssignmendFromMethodInvocationToPropertyNotDisposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not disposed..
        /// </summary>
        internal static string AssignmendFromMethodInvocationToPropertyNotDisposedMessageFormat {
            get {
                return ResourceManager.GetString("AssignmendFromMethodInvocationToPropertyNotDisposedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed objects assinged to a property, originated from a method invocation..
        /// </summary>
        internal static string AssignmendFromMethodInvocationToPropertyNotDisposedTitle {
            get {
                return ResourceManager.GetString("AssignmendFromMethodInvocationToPropertyNotDisposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of object creation is assigned to a field that is never disposed..
        /// </summary>
        internal static string AssignmendFromObjectCreationToFieldNotDisposedDescription {
            get {
                return ResourceManager.GetString("AssignmendFromObjectCreationToFieldNotDisposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not disposed..
        /// </summary>
        internal static string AssignmendFromObjectCreationToFieldNotDisposedMessageFormat {
            get {
                return ResourceManager.GetString("AssignmendFromObjectCreationToFieldNotDisposedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed objects assinged to a field, originated in an object creation..
        /// </summary>
        internal static string AssignmendFromObjectCreationToFieldNotDisposedTitle {
            get {
                return ResourceManager.GetString("AssignmendFromObjectCreationToFieldNotDisposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of object creation is assigned to a property that is never disposed..
        /// </summary>
        internal static string AssignmendFromObjectCreationToPropertyNotDisposedDescription {
            get {
                return ResourceManager.GetString("AssignmendFromObjectCreationToPropertyNotDisposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not disposed..
        /// </summary>
        internal static string AssignmendFromObjectCreationToPropertyNotDisposedMessageFormat {
            get {
                return ResourceManager.GetString("AssignmendFromObjectCreationToPropertyNotDisposedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed objects assinged to a property, originated in an object creation..
        /// </summary>
        internal static string AssignmendFromObjectCreationToPropertyNotDisposedTitle {
            get {
                return ResourceManager.GetString("AssignmendFromObjectCreationToPropertyNotDisposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undisposed local variables.
        /// </summary>
        internal static string NotDisposedLocalVariableDescription {
            get {
                return ResourceManager.GetString("NotDisposedLocalVariableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable is not disposed.
        /// </summary>
        internal static string NotDisposedLocalVariableMessageFormat {
            get {
                return ResourceManager.GetString("NotDisposedLocalVariableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks undisposed local variables..
        /// </summary>
        internal static string NotDisposedLocalVariableTitle {
            get {
                return ResourceManager.GetString("NotDisposedLocalVariableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disposable is not disposed..
        /// </summary>
        internal static string NotDisposedMessageFormat {
            get {
                return ResourceManager.GetString("NotDisposedMessageFormat", resourceCulture);
            }
        }
    }
}
